name: Build Mission 26
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build APK with Buildozer
        uses: kivy/buildozer-action@latest
        with:
          buildozer_version: master
          python_version: 3.8
